import { Keypair, PublicKey } from '@solana/web3.js';

export const clearingHousePublicKey = new PublicKey(
    'AsW7LnXB9UA1uec9wi9MctYTgTz7YH9snhxd16GsFaGX'
);
export const pythPublicKey = new PublicKey(
    '6bgJrRngVsFzCFkjd5PkVKMtb1C3JXgYnEFLhkJPtnEp'
);
export const error_codes = [
    "Clearing house not collateral account owner",
    "Clearing house not insurance account owner",
    "Insufficient deposit",
    "Insufficient collateral",
    "Sufficient collateral",
    "Max number of positions taken",
    "Admin Controls Prices Disabled",
    "Market Index Not Initialized",
    "Market Index Already Initialized",
    "User Account And User Positions Account Mismatch",
    "User Has No Position In Market",
    "Invalid Initial Peg",
    "AMM repeg already configured with amt given",
    "AMM repeg incorrect repeg direction",
    "AMM repeg out of bounds pnl",
    "Slippage Outside Limit Price",
    "Trade Size Too Small",
    "Price change too large when updating K",
    "Admin tried to withdraw amount larger than fees collected",
    "Math Error",
    "Conversion to u128/u64 failed with an overflow or underflow",
    "Clock unavailable",
    "Unable To Load Oracles",
    "Oracle/Mark Spread Too Large",
    "Clearing House history already initialized",
    "Exchange is paused",
    "Invalid whitelist token",
    "Whitelist token not found",
    "Invalid discount token",
    "Discount token not found",
    "Invalid referrer",
    "Referrer not found",
    "InvalidOracle",
    "OracleNotFound",
    "Liquidations Blocked By Oracle",
    "Can not deposit more than max deposit",
    "Can not delete user that still has collateral",
    "AMM funding out of bounds pnl",
    "Casting Failure",
    "Invalid Order",
    "User has no order",
    "Order Amount Too Small",
    "Max number of orders taken",
    "Order does not exist",
    "Order not open",
    "CouldNotFillOrder",
    "Reduce only order increased risk",
    "Order state already initialized",
    "Unable to load AccountLoader",
    "Trade Size Too Large",
    "Unable to write to remaining account",
    "User cant refer themselves",
    "Did not receive expected referrer",
    "Could not deserialize referrer",
    "Market order must be in place and fill",
    "User Order Id Already In Use",
    "No positions liquidatable",
    "Invalid Margin Ratio",
    "Cant Cancel Post Only Order",
    "InvalidOracleOffset",
    "CantExpireOrders",
    "AMM repeg mark price impact vs oracle too large",
]